//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.VentaDetalle = new HashSet<VentaDetalle>();
        }
    
        public int IdProducto { get; set; }
        public string Descripcion { get; set; }
        public bool Estado { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Foto { get; set; }
        public Nullable<double> CostoCompra { get; set; }
        public Nullable<double> CostoVenta { get; set; }
        public Nullable<int> CantidadDisponible { get; set; }
        public int IdBodega { get; set; }
    
        public virtual Bodega Bodega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentaDetalle> VentaDetalle { get; set; }
    }
}
