//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentaDetalle
    {
        public int IdVentaDetalle { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public double Valor { get; set; }
        public bool Estado { get; set; }
        public int IdProducto { get; set; }
        public int IdVentaEncabezado { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual VentaEncabezado VentaEncabezado { get; set; }
    }
}
